apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: copilot-agent-runners
  namespace: actions-runner-system
spec:
  replicas: 2
  template:
    spec:
      repository: isNotOkay/self-hosted-github-copilot-agent-runner
      labels:
        - copilot-agent
        - arc-runner
      ephemeral: true
      image: ghcr.io/isnotokay/copilot-agent-runner:latest

      env:
        - name: GITHUB_HOST
          value: "github.com"
        - name: GITHUB_SERVER_URL
          value: "https://github.com"
        - name: GITHUB_API_URL
          value: "https://api.github.com"
