apiVersion: actions.github.com/v1alpha1
kind: AutoScalingRunnerSet
metadata:
  name: copilot-agent-runners          # reference this in runs-on:
  namespace: actions-runner-system
spec:
  githubConfigUrl: https://github.com/isNotOkay/self-hosted-github-copilot-agent-runner
  githubConfigSecret: arc-ghapp-secret                # <-- name of your GitHub App secret
  maxRunners: 10
  minRunners: 0
  template:
    spec:
      image: ghcr.io/isnotokay/copilot-agent-runner:latest
      ephemeral: true
      labels:
        - copilot-agent
        - arc-runner
      env:
        - name: GITHUB_HOST
          value: github.com
        - name: GITHUB_SERVER_URL
          value: https://github.com/
        - name: GITHUB_API_URL
          value: https://api.github.com/
